name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: Thiagosantos088  # Substitua pelo seu usuário do GitHub
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
